jack.rules = [
    {
        matches = [
            {
                client.name = "gx_head_amp"
            }
        ]
        actions = {
            update-props = {
                node.latency = 64/96000
                node.rate = 1/96000
                node.quantum = 64/96000
                node.lock-quantum = true
                node.force-quantum = 64
            }
        }
    }
    {
        matches = [
            {
                client.name = "gx_head_fx"
            }
        ]
        actions = {
            update-props = {
                node.latency = 64/96000
                node.rate = 1/96000
                node.quantum = 64/96000
                node.lock-quantum = true
                node.force-quantum = 64
            }
        }
    }
    {
        matches = [
            {
                client.name = "jack_delay"
            }
        ]
        actions = {
            update-props = {
                node.latency = 64/96000
                node.rate = 1/96000
                node.quantum = 64/96000
                node.lock-quantum = true
                node.force-quantum = 64
            }
        }
    }
    {
        matches = [
            {
                client.name = "Neuralrack"
            }
        ]
        actions = {
            update-props = {
                node.latency = 64/96000
                node.rate = 1/96000
                node.quantum = 64/96000
                node.lock-quantum = true
                node.force-quantum = 64
            }
        }
    }
]
